name: 'Check secret'
description: 'Check secret'
inputs:
  secret:
    description: 'Secret to check'
    required: true
outputs:
  defined:
    description: "Boolean of whether secret is defined"
    value: ${{ steps.secret.outputs.defined }}
runs:
  using: 'composite'
  steps:
    - name: Check secrets
      id: secret
      env:
        secret: ${{ inputs.secret }}
      shell: bash
      run: |
        if [ "$secret" == "" ]; then
          echo "defined=false" >> $GITHUB_OUTPUT
        else
          echo "defined=true" >> $GITHUB_OUTPUT
        fi
