name: "Validate dependencies"
description: "Validate dependencies"
runs:
  using: "composite"
  steps:
      - name: Ensure that Yarn V3 dependencies are installed
        run: yarn install
        shell: bash
      - name: Check dependencies
        run: yarn audit --groups "dependencies" --level moderate
        shell: bash
